### ISSUE TITLE
Change the granularity of `Last Seen` fields

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-explorer#85]
`a few seconds ago` is not so helpful. It should be `4 seconds ago` and `8 seconds ago`.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/9711879/55378273-50567280-5553-11e9-8791-388522e7d313.png">

**Comment by sgkim126** [comment]
@joojis You should update the page every second if you use relative time. I think it's better to use the exact time instead of relative time.

**Comment by joojis** [comment]
@sgkim126 Agree. @cubismic Let's change it to use exact time

**Comment by cubismic** [comment]
![exact time](https://user-images.githubusercontent.com/31873152/55454324-77c44280-561a-11e9-96d1-b3f992e59513.png)

![relative time](https://user-images.githubusercontent.com/31873152/55454551-439d5180-561b-11e9-8d49-ac71a5469acf.png)

 I think relative time looks prettier (maybe due to the font and the string length). 
 So how about this?
 > until 1 hour, display `~ seconds ago`, `~ minutes ago` and no `a few seconds ago`
 > for today, display `Today HH:mm:ss`
 > until same year `MM/DD HH:mm:ss`
 > after that, `MM/DD/YYYY HH:mm:ss`

**Comment by joojis** [comment]
@cubismic Looks good to me.

@sgkim126 How about you? I think we don't need to update the component every second. The interval can be 5s or so.

**Comment by sgkim126** [comment]
@joojis @cubismic
If the 5 seconds error is fine, I'm okay too.
